version: '2.2'

services:
    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        mem_limit: 4000000000
        memswap_limit: 6000000000
        mem_reservation: 1024m
        privileged: true
        cpu_count: 2
        restart: always
        hostname: ${GITLAB_HOST_NAME}
        container_name: gitlab
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://${GITLAB_HOST_NAME}:${GITLAB_HOST_PORT}'
                gitlab_rails['backup_keep_time'] = ${GITLAB_BACKUP_LIFETIME}
                gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}

        ports:
            - '${GITLAB_HOST_PORT}:${GITLAB_HOST_PORT}'
            - '${GITLAB_SSH_PORT}:${GITLAB_SSH_PORT}'
        volumes:
            - '${GITLAB_VOLUMES_ROOT}/config:/etc/gitlab'
            - '${GITLAB_VOLUMES_ROOT}/logs:/var/log/gitlab'
            - '${GITLAB_VOLUMES_ROOT}/data:/var/opt/gitlab'
