version: '3'

services:
    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        hostname: ${GITLAB_HOST_NAME}
        container_name: gitlab
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://${GITLAB_HOST_NAME}:${GITLAB_HOST_PORT}'

        ports:
            - '${GITLAB_HOST_PORT}:${GITLAB_HOST_PORT}'
            - '${GITLAB_SSH_PORT}:22'
        # volumes:
        #     - '${GITLAB_VOLUMES_ROOT}/config:/etc/gitlab'
        #     - '${GITLAB_VOLUMES_ROOT}/logs:/var/log/gitlab'
        #     - '${GITLAB_VOLUMES_ROOT}/data:/var/opt/gitlab'
