web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: '192.168.0.133'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://192.168.0.133:9090'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '9090:9090'
    - '2224:22'
